config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	resources :likes
  end
  resources :users
  #get 'posts', to: 'posts#index', as: :posts
  resources :search, only: [:index]
  root 'posts#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	validates :body, presence: true
	validates :title, presence: true
	validates :title, length: { maximum: 50 }
	validates :title, length: { minimum: 3 }
	validates :image, presence: {:message => " must be attached to the post"}
	validates :body, length: { minimum: 20 }
  	validates :body, length: { maximum: 500 }
	paginates_per 3
	belongs_to :user
	mount_uploader :image, ImageUploader
	include PgSearch
	pg_search_scope :search, against: [:title, :body]
	has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

   before_action :find_post

	def create
	  if already_liked?
	    flash[:notice] = "You can't like more than once"
	  else
	    @post.likes.create(user_id: current_user.id)
	  end
	  redirect_to post_path(@post)
	end
	
	
	def destroy
		
	  if !(already_liked?)
	    flash[:notice] = "Cannot unlike"
	  else
	  	@like = @post.likes.find(params[:id])
	    @like.destroy
	  end
	  redirect_to post_path(@post)
	end


  private

  def already_liked?
	  Like.where(user_id: current_user.id, post_id:
	  params[:post_id]).exists?
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper 
  before_action :set_post, only: [:show, :edit, :update, :destroy, :sort]
  before_action :authenticate_user!, except: [:index, :show, :sort]
  # GET /posts
  # GET /posts.json
  def index
    if !params[:query].blank?
      @posts = Post.search(params[:query])

    elsif params[:sort] == "liked"
       @posts = Post.left_joins(:likes).group(:id).order('COUNT(likes.id) DESC')

    elsif params[:sort]
      @posts = Post.reorder(params[:sort] + " " + params[:direction])
    else
       @posts = Post.all
    end

    @posts = @posts.page(params[:page])

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new

  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
    @posts = Post.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title)
		direction = column == params[:sort] && params[:direction] == "asc" ? "desc" : "asc"
		link_to title, :sort => column, :direction => direction
	end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper 
  
end
	

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>

    <nav class = "navbar navbar-expand-lg navbar-dark" style ="background-color: darkslategray;" id="nav-traka" >
  	   
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div id="search_bar" style="display: inline;">
          <%= form_tag posts_path, method: :get do %>
            <input type="text" name="query" id="query" placeholder= "Search query" value="<%= params[:query] %>">
            <input type="submit" name="commit" value="Search" class="btn btn-default">
          <%end%>
        </div>
          <ul class ="navbar-nav ml-auto" id="nav-tipke">
        
            <li class="nav-item"><% if !user_signed_in? %><%= link_to "Sing up", new_user_registration_path %> <% end %></li>
            <li class="nav-item"> <% if user_signed_in? %>
                                    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
                                  <% else %>
                                    <%= link_to('Login', new_user_session_path) %>  
                                  <% end %>
            </li>
            <li class="nav-item" style="color: white">
                <p>Welcome <strong><%=
                  if user_signed_in? 
                      User.find(current_user.id).email
                  else
                      "Guest"    
                  end
                      %></strong>
                </p>
            </li>
          </ul>
        </div>
        
     </nav>  
   

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<head>
      <script type="text/javascript">
        tinyMCE.init({
          force_br_newlines : true,
          force_p_newlines : false,
          forced_root_block : '' // Needed for 3.x
        });
    </script>
</head>
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class= "field">
      <%= form.file_field :image %>
  </div>
  <div class="field" style="width: 60vw;">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body, :rows => 20, :cols => 30, :class => "tinymce"%>
    <%= tinymce %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
  <h1 style="text-align: center; ">Posts</h1>

       <%=paginate @posts%>
    <br><br>

<div id="post_options" >
  <%= link_to 'New Post', new_post_path, class:"btn btn-primary", id:"tipka"%>
  <%= sortable "user_id" , "Sort by user"%>
  <%= sortable  "created_at", "Sort by date"%>
</div>
    
  <div class="blog_posts">
    <% @posts.each do |post| %>
    <div class="blog_post"  >   
        <h1 class="naslov"><%= post.title %></h1>
        <div class="image_body"><%= image_tag post.image_url(:thumb) if post.image?%></div>
        <p class="body_post"><%= sanitize post.body %></p>
        <p class="email_post" style="color: darkslategray; text-align: center; ">Uploaded by: <%= post.user.email %></p>
        <div class="manage_body">
          <%= link_to 'Show', post %>
          <% if user_signed_in? %>
          <p id ="like_dislike">
          <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
              <% if pre_like %>
                <%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete, class:"btn btn-primary" %>
                <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%>
    
              <% else %>
                <%= button_to 'Like', post_likes_path(post), method: :post, class:"btn btn-primary" %>
                <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%>
              <% end %>
          </p>    
          <%end%>    
          <% if post.user == current_user %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %> 
        </div>
    <% end %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div id="new_post">
	<h1>New Post</h1>

	<%= render 'form', post: @post %>

	<%= link_to 'Back', posts_path %>
</div>

<style type="text/css">
		#new_post {
			margin: 0 auto;
			margin-top: 12vh;
			justify-content: center;
			align-items: center;
			width: 64vw;
			background-color: rgba(255,255,255, 0.6);
			padding: 50px;
		}
</style>

app/views/posts/show.html.erb
<head>
	<style type="text/css">
		#show_post {
		
		
			justify-content: center;
			align-items: center;
			width: 20vw;
			background-color: rgba(255,255,255, 0.6);
			padding: 50px;
		}
	</style>
</head>
<div id = "show_post">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Title:</strong>
	  <br>
	  <%= @post.title %>
	</p>

	<p>
	  <strong>Body:</strong>
	  <%= sanitize @post.body %>
	</p>
	<p>
	  <strong>Image:</strong>
	  <div class="image_body"><%= image_tag @post.image_url(:thumb) if @post.image?%></div>
	</p>

	<p class="email_post">
		<strong>Uploaded by:</strong>
		<p><%= @post.user.email %></p>
	</p>
	<br><br><br>
	<div style="text-align: center;">
	<%= link_to 'Edit', edit_post_path(@post) %> |
	<%= link_to 'Back', posts_path %>
</div>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<br><br><br>
<h2>Your bio:</h2>
<p><%= @user.bio %></p>
<br>
<h2>Your posts:</h2>


<% @user.posts.each do |post| %>
	<p><%= sanitize post.body %></p>
	<p><%= post.user_id %></p>
	<p><%= @user.id %></p>
<%end%>